theme: minima
exclude: [README.md]

# TODO: zmenit skolsky rok podla potreby
title: Methods in Bioinformatics 2025/26

moodle: 2160

header_pages:
  - index.md
  - Rules.md
  - Materials.md
  - Tasks.md
  - Project.md
  - Journal_club.md
  - Exam.md
